const mockCars = [
  {
    id: 1,
    make: 'Ford',
    model: 'Fusion',
    year: 2012,
    mileage: 190000,
    image: 'https://atcimages.kbb.com/hn/c/6cfc871dc210430097f3eafce8fa56f5.jpg',
    price: 4000,
    description: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.',
    street: '123 Main Street',
    city: 'Farmville',
    state: 'FL',
    zip: '45321',
    user_id: null
  },
  {
    id: 2,
    make: 'Ford',
    model: 'Branco',
    year: 2023,
    mileage: 56,
    image: 'https://imageio.forbes.com/specials-images/imageserve/63f52ede45330fcb0260713c/2023-Ford-Bronco-Everglades/960x0.jpg?format=jpg&width=960',
    price: 64000,
    description: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.',
    street: '5 East Street',
    city: 'Testville',
    state: 'MN',
    zip: '89898',
    user_id: null
  },
  {
    id: 3,
    make: 'Toyota',
    model: 'BRZ',
    year: 2016,
    mileage: 106589,
    image: 'https://cdn.carbuzz.com/gallery-images/1600/393000/100/393181.jpg',
    price: 12000,
    description: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.',
    street: '5 East Street',
    city: 'Testville',
    state: 'MN',
    zip: '89898',
    user_id: 1
  },
  {
    id: 4,
    make: 'Bugatti',
    model: 'Chiron Super Sport 300+',
    year: 2019,
    mileage: 1300,
    image: 'https://www.bugatti.com/fileadmin/_processed_/sei/p426/se-image-06a67179016e87615a9f34fb3781271b.jpg',
    price: 3900000,
    description: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.',
    street: '1 Rich Way',
    city: 'Cashtown',
    state: 'OH',
    zip: '88445',
    user_id: null
  },
  {
    id: 5,
    make: 'Chevrolet',
    model: 'Corvette Stingray',
    year: 2023,
    mileage: 100,
    image: 'https://www.vinylwrap.org/wp-content/uploads/2018/10/13188034_1130771763653079_78195089_n.jpg',
    price: 62000,
    description: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.',
    street: '69 Freaky Street',
    city: 'Bamville',
    state: 'NY',
    zip: '11221',
    user_id: 2
  },
  {
    id: 6,
    make: 'Porsche',
    model: '911',
    year: 2020,
    mileage: 16894,
    image: 'https://media.ed.edmunds-media.com/porsche/911/2020/oem/2020_porsche_911_coupe_carrera-4_fq_oem_1_1600.jpg',
    price: 103000,
    description: 'Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla nisi laboris ex in Lorem sunt duis officia eiusmod. Aliqua reprehenderit commodo ex non excepteur duis sunt velit enim. Voluptate laboris sint cupidatat ullamco ut ea consectetur et est culpa et culpa duis.',
    street: '8899 Buck Puck',
    city: 'FizzBuzz',
    state: 'GA',
    zip: '67676',
    user_id: null
  },
]

export default mockCars
